CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(30)                             NOT NULL,
    last_name  VARCHAR(30)                             NOT NULL,
    email      VARCHAR(100)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    birth_date date,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);